In [1]:
import pandas as pd

In [2]:
data = [[1, 3.5], [2, 3.65], [3, 4.0], [4, 3.85], [5, 4.0], [6, 3.65]]
scores = pd.DataFrame(data, columns=['id', 'score']).astype({'id':'Int64', 'score':'Float64'})

In [3]:
df = scores.sort_values(by='score', ascending=False)

In [4]:
df

   id  score
4   5    4.0
2   3    4.0
3   4   3.85
1   2   3.65
5   6   3.65
0   1    3.5

In [20]:
df['score']

4     4.0
2     4.0
3    3.85
1    3.65
5    3.65
0     3.5
Name: score, dtype: Float64

In [31]:
df['rank'] = df.sort_values(by='score', ascending=False).rank(method='dense', ascending=False)['score'].astype(int)

In [32]:
df.drop(columns=['id']).reset_index(drop=True)

   score  rank
0    4.0     1
1    4.0     1
2   3.85     2
3   3.65     3
4   3.65     3
5    3.5     4

In [16]:
pd.DataFrame({
    df['score']: [df['score'].rank(method = 'dense', ascending=False).astype(int)]
})

TypeError: unhashable type: 'Series'

In [ ]:
.rank()

In [6]:
s = pd.Series([100, 90, 90, 80])

In [8]:
s.rank(), s

(0    4.0
 1    2.5
 2    2.5
 3    1.0
 dtype: float64,
 0    100
 1     90
 2     90
 3     80
 dtype: int64)